export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",

  UNAUTHORIZED = "UNAUTHORIZED",

  FORBIDDEN = "FORBIDDEN",

  NOT_FOUND = "NOT_FOUND",

  INTERVIEW_NOT_FOUND = "INTERVIEW_NOT_FOUND",

  INTERVIEW_EXPIRED = "INTERVIEW_EXPIRED",

  INVALID_CONFIGURATION = "INVALID_CONFIGURATION",

  AI_SERVICE_ERROR = "AI_SERVICE_ERROR",

  REDIS_ERROR = "REDIS_ERROR",

  DATABASE_ERROR = "DATABASE_ERROR",

  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}